### ISSUE TITLE
More advance coming soon page for 2024/2025

### ISSUE THREAD

**Issue by mcictsmain** [mcicts-usr/dev-site#1]

**Comment by thisisdineth** [comment]
Added time counter for the page , this look more updative 
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MCICTS • Under updating</title>
    <link rel="stylesheet" href="./styles.css">
    <style>
        a {
          text-decoration: none; /* Removes the underline */
          color: rgb(81, 81, 242); /* Sets the text color to blue */
        }
        p{
            color: #f5f5f5;
        }
        footer {
          background-color: #232326; /* Deep background for a professional look */
          color: #f5f5f5; /* Light text for contrast */
          text-align: center; /* Center the text */
          padding: 20px 10px; /* Add spacing for a neat appearance */
          font-family: 'Arial', sans-serif; /* Clean font */
          font-size: 1.2rem; /* Slightly larger text */
          font-weight: bold; /* Make the text appear confident */
          box-shadow: 0 -5px 10px rgba(0, 0, 0, 0.5); /* Add shadow for floating effect */
          border-top: 3px solid #f1c40f; /* Add a golden border for prestige */
        }
        .desc-text {
          font-size: 1.5rem;
          color: #333;
        }
        .desc-text p {
          margin: 10px 0;
        }
    </style>
</head>
<body>
    <div class="main">
        <div>
            <img class="img" src="./Transparent BG (White Letters) NE.png" alt="MCICTS Logo">
        </div>
        <div class="desc-text">
            <p>Hello, mcicts.lk official site is under updating for the 2024/2025 batch.</p>
            <p>If you want to join MCICTS, <a href="https://register.mcicts.lk/">Click here</a></p>
            
            <p id="date-container">Loading date...</p> 

            <script>
              // Get the current date
              const currentDate = new Date();

              // List of month names
              const monthNames = [
                "January", "February", "March", "April", "May", "June", 
                "July", "August", "September", "October", "November", "December"
              ];

              // Format the date as "dd/mm/yy"
              const day = String(currentDate.getDate()).padStart(2, '0');  // Adds leading zero if necessary
              const month = String(currentDate.getMonth() + 1).padStart(2, '0');  // Months are zero-based, so adding 1
              const year = String(currentDate.getFullYear()).slice(-2);  // Get the last 2 digits of the year

              // Format the full date and month name
              const formattedDate = `${currentDate.getFullYear()} ${monthNames[currentDate.getMonth()]} Updates (${day}/${month}/${year})`;

              // Insert the date into the paragraph with ID "date-container"
              document.getElementById("date-container").innerText = formattedDate;
            </script>

        </div>
    </div>
</body>
<footer>Mahanama College ICT Society 2024/2025</footer>
</html>
